-- a) Calculate the number of employees in different salary grades for each department using COUNT aggregation function instead of SUM.

SELECT DEPARTMENT_ID, 
COUNT(CASE WHEN SALARY>15000 THEN EMPLOYEE_ID END) "A+",
COUNT(CASE WHEN SALARY>=10000 AND SALARY < 15000 THEN EMPLOYEE_ID END) "A",
COUNT(CASE WHEN SALARY>=5000 AND SALARY < 10000 THEN EMPLOYEE_ID END) "B",
COUNT(CASE WHEN SALARY<5000 THEN EMPLOYEE_ID END) "C"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

-- c) Write the query to show total employees working in the employee’s department and in the employee’s manager’s department
--    without using WITH clause. You can use subqueries in the FROM clause.


SELECT E1.FIRST_NAME, E3.EMPCOUNT "Emp Count Employee Dept", E4.EMPCOUNT "Emp Count Maneger Dept"
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON (E1.MANAGER_ID = E2.EMPLOYEE_ID)
JOIN 
(
	SELECT DEPARTMENT_ID, COUNT(*) EMPCOUNT
	FROM EMPLOYEES 
	GROUP BY DEPARTMENT_ID
)
E3 ON (E1.DEPARTMENT_ID = E3.DEPARTMENT_ID) 
JOIN 
(
	SELECT DEPARTMENT_ID, COUNT(*) EMPCOUNT
	FROM EMPLOYEES 
	GROUP BY DEPARTMENT_ID
)
E4 ON (E2.DEPARTMENT_ID = E4.DEPARTMENT_ID) 
ORDER BY E1.EMPLOYEE_ID ASC;